# -*- coding: utf-8 -*-
"""letterboxd_scraper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_fQTbHZrxEM-rbxo7jlPYIHQ3QCnYV5C
"""

import sys
!{sys.executable} -m pip install undetected-chromedriver
   """
Letterboxd Bipartite Graph Scraper
====================================
Scrapes reviewer usernames per film from Letterboxd.
Uses undetected-chromedriver to bypass Cloudflare, then
transfers session cookies to requests for fast AJAX scraping.

Usage:
    Run the cell. It will open a Chrome window for warmup,
    then scrape all films using the requests session.

Requirements:
    pip install undetected-chromedriver selenium requests beautifulsoup4 pandas
"""

import os
import re
import time
import random
import pandas as pd
import requests
from bs4 import BeautifulSoup
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import WebDriverException
from selenium.common.exceptions import TimeoutException, WebDriverException

# ─── CONFIG ───────────────────────────────────────────────────────────────────

BASE         = "https://letterboxd.com"
PROFILE_DIR  = os.path.abspath("./chrome_profile_letterboxd")
CHROME_VER   = 145          # match your Chrome major version (chrome://version)
PAGE_TIMEOUT = 60           # seconds before page load gives up

MIN_SLEEP        = 4.0      # minimum seconds between film requests
MAX_SLEEP        = 9.0      # maximum seconds between film requests
LONG_PAUSE_EVERY = 5        # take a long pause every N films
LONG_PAUSE_RANGE = (20, 45) # seconds for long pause

TARGET_USERS_PER_FILM = 160 # how many reviewers to collect per film

# ─── HELPERS ──────────────────────────────────────────────────────────────────

def polite_sleep():
    time.sleep(random.uniform(MIN_SLEEP, MAX_SLEEP))


def long_pause():
    duration = random.uniform(*LONG_PAUSE_RANGE)
    print(f"  [long pause] sleeping {duration:.0f}s...")
    time.sleep(duration)


# ─── BROWSER (warmup only) ────────────────────────────────────────────────────

def make_driver() -> uc.Chrome:
    opts = uc.ChromeOptions()
    opts.add_argument(f"--user-data-dir={PROFILE_DIR}")
    opts.add_argument("--profile-directory=Default")
    opts.add_argument("--window-size=1400,900")
    opts.add_argument("--lang=en-US")
    driver = uc.Chrome(
    options=opts,
    use_subprocess=True,
    version_main=145  # Explicitly set to 122 for 122.0.6261.57
)
    driver.set_page_load_timeout(PAGE_TIMEOUT)
    return driver


def is_blocked(driver) -> bool:
    t   = (driver.title or "").lower()
    src = (driver.page_source or "").lower()
    return (
        "just a moment" in t
        or "cf-browser-verification" in src
        or ("captcha" in src and "cloudflare" in src)
        or "enable javascript" in src
    )


def maybe_accept_cookies(driver):
    for css in [
        "button#onetrust-accept-btn-handler",
        "button[aria-label='Accept cookies']",
        "button[title='Accept']",
    ]:
        btns = driver.find_elements(By.CSS_SELECTOR, css)
        if btns:
            try:
                btns[0].click()
                return
            except WebDriverException:
                pass


def warmup_manual(driver):
    """
    Open Letterboxd in the browser so Cloudflare clears.
    User must press ENTER once normal content is visible.
    """
    print("\nWARMUP: Opening Letterboxd home...")
    driver.get(BASE + "/")
    time.sleep(3)
    maybe_accept_cookies(driver)

    print("WARMUP: Opening a search page to clear CF for /search/ path...")
    driver.get(BASE + "/search/reviews/inception/")
    time.sleep(3)

    print("\n" + "="*50)
    print("ACTION REQUIRED:")
    print("  1. Complete any Cloudflare 'Just a moment' challenge")
    print("  2. Log in to Letterboxd if prompted (optional but helps)")
    print("  3. When you see normal Letterboxd content, come back here")
    print("="*50)
    input("Press ENTER when ready > ")

    if is_blocked(driver):
        print("WARNING: Page still looks blocked — you may want to restart.")
    else:
        print(f"Warmup OK. Page title: {driver.title}")


def get_session_from_driver(driver) -> requests.Session:
    """
    Copy the browser's Cloudflare-cleared cookies into a requests.Session
    so we can make fast AJAX calls without the browser."""
    session = requests.Session()
    for cookie in driver.get_cookies():
        session.cookies.set(cookie["name"], cookie["value"])
    session.headers.update({
        "User-Agent":        driver.execute_script("return navigator.userAgent"),
        "X-Requested-With":  "XMLHttpRequest",
        "Referer":           BASE,
        "Accept":            "text/html, */*; q=0.01",
        "Accept-Language":   "en-US,en;q=0.9",
    })
    print("Session built with browser cookies.")
    return session

def wait_for_clearance(driver, timeout=120):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if not is_blocked(driver):
            return True
        time.sleep(1.5)
    return False

def scrape_film_users(driver, slug: str, target: int = TARGET_USERS_PER_FILM) -> list[dict]:
    """
    Scrape reviewers from /film/{slug}/reviews/ pages.
    Each page has ~12 reviewers. Paginate until target is reached.
    """
    all_rows = []
    seen_users = set()
    page = 1
    max_pages = 20  # safety limit

    while len(seen_users) < target and page <= max_pages:
        if page == 1:
            url = f"{BASE}/film/{slug}/reviews/"
        else:
            url = f"{BASE}/film/{slug}/reviews/page/{page}/"

        driver.get(url)

        if not wait_for_clearance(driver, timeout=60):
            print(f"  [blocked] on page {page}")
            break

        # Check for 404 / film not found
        if "not found" in driver.title.lower() or "sorry, we can't find" in driver.page_source.lower():
            print(f"  [404] film not found on Letterboxd - bad slug")
            return []  # skip this film entirely
        # Wait for reviews to load
        try:
            WebDriverWait(driver, 20).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, "a.avatar"))
            )
        except TimeoutException:
            print(f"  [empty] no reviews on page {page}")
            break

        # Parse usernames from avatars
        avatars = driver.find_elements(By.CSS_SELECTOR, "a.avatar img[alt]")
        if not avatars:
            print(f"  [done] no more pages")
            break

        new_users = 0
        for img in avatars:
            user = img.get_attribute("alt")
            if user and user not in seen_users:
                seen_users.add(user)
                all_rows.append({
                    "user_id": user.strip(),
                    "film_slug": slug,
                    "film_display": slug,  # we can enhance this later if needed
                })
                new_users += 1

        print(f"  [page {page}] +{new_users} new | total: {len(seen_users)}")

        if new_users == 0:  # no new users on this page, we've hit duplicates or the end
            print(f"  [done] no new users on page {page}")
            break

        page += 1
        time.sleep(random.uniform(1.5, 3.0))

    print(f"  [total] {len(seen_users)} unique users")
    return all_rows


# ─── TEST RUN (10 films) ──────────────────────────────────────────────────────

def run_test():
    # Load first 5 from the production CSV
    slugs_df = pd.read_csv("films_500.csv")
    test_slugs = slugs_df["film_slug"].dropna().str.strip().head(5).tolist()

    output_csv = "test_edges_5films.csv"
    all_rows = []

    print(f"Testing with: {test_slugs}")

    driver = make_driver()
    try:
        warmup_manual(driver)

        for idx, slug in enumerate(test_slugs, start=1):
            print(f"\n[{idx}/{len(test_slugs)}] {slug}")
            try:
                rows = scrape_film_users(driver, slug)
                print(f"  [done] {len(set(r['user_id'] for r in rows))} users collected")
                all_rows.extend(rows)
            except Exception as e:
                print(f"  [failed] {e}")

            polite_sleep()
            if idx % LONG_PAUSE_EVERY == 0:
                long_pause()

    finally:
        edges_df = pd.DataFrame(all_rows).drop_duplicates(subset=["user_id", "film_slug"])
        edges_df.to_csv(output_csv, index=False)
        print(f"\n[SAVED] {len(edges_df)} edges → {output_csv}")
        driver.quit()


# ─── PRODUCTION RUN (500 films) ───────────────────────────────────────────────

def run_production(
    input_csv:  str = "films_500.csv",
    output_csv: str = "edges_500films.csv",
):
    # Load slug list
    slugs_df = pd.read_csv(input_csv)
    slugs    = slugs_df["film_slug"].dropna().str.strip().tolist()
    print(f"Loaded {len(slugs)} slugs from {input_csv}")

    # Resume support — skip already-finished slugs
    if os.path.exists(output_csv):
        done_df    = pd.read_csv(output_csv)
        done_slugs = set(done_df["film_slug"].unique())
        slugs      = [s for s in slugs if s not in done_slugs]
        all_rows   = done_df.to_dict("records")
        print(f"Resuming: {len(done_slugs)} done, {len(slugs)} remaining")
    else:
        all_rows = []

    driver = make_driver()
    try:
        warmup_manual(driver)


        for idx, slug in enumerate(slugs, start=1):
            print(f"\n[{idx}/{len(slugs)}] {slug}")

            try:
                rows = scrape_film_users(driver, slug)
                n    = len(set(r["user_id"] for r in rows))
                print(f"  [done] {n} users collected")
                all_rows.extend(rows)
            except Exception as e:
                print(f"  [failed] {e}")

            # Checkpoint every 10 films
            if idx % 10 == 0:
                edges_df = pd.DataFrame(all_rows).drop_duplicates(
                    subset=["user_id", "film_slug"]
                )
                edges_df.to_csv(output_csv, index=False)
                print(f"  [checkpoint] {len(edges_df)} edges saved")

            polite_sleep()
            if idx % LONG_PAUSE_EVERY == 0:
                long_pause()

    finally:
        edges_df = pd.DataFrame(all_rows).drop_duplicates(subset=["user_id", "film_slug"])
        edges_df.to_csv(output_csv, index=False)
        print(f"\n[DONE] {len(edges_df)} edges → {output_csv}")
        driver.quit()


# ─── ENTRY POINT ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    #run_test()
   run_production("films_500_genre_strict.csv", "edges_genre_strict.csv")